---
- name: Copy CSV to web server
  hosts: web

  vars_files:
  - vars/aruba.yaml

  tasks:
    - name: Copy CSV to web server
      become: yes
      ansible.builtin.copy:
        src: "{{ csv_path }}/{{ csv_filename }}"
        dest: "/var/www/html/{{ csv_filename }}"
    