---
# This can be an example of closing / update a change request 
- name: Close a Change Request
  hosts: localhost
  gather_facts: no
  connection: local

  tasks:
 
    - name: Transition to Review
      servicenow.itsm.change_request:
        state: "review"      
        assignment_group: "{{ assignment_group }}"
        number: "{{ request_number }}"
        
    - name: Close Change Request       
      servicenow.itsm.change_request:
        state: "closed"
        close_code: "successful"
        close_notes: "Closed"
        assignment_group: "{{ assignment_group }}"
        number: "{{ request_number }}"



