---
collections:
  
  - name: ansible.netcommon
  # https://github.com/aruba/aos-switch-ansible-collection
  - name: arubanetworks.aos_switch
  # https://github.com/ansible-collections/servicenow.itsm
  - name: servicenow.itsm
  # https://github.com/ansible-collections/community.general
  - name: community.general
